### ISSUE TITLE
Can't build week01

### ISSUE THREAD

**Issue by Carlosted** [input-output-hk/plutus-pioneer-program#39] opened 2021-08-13 15:43 UTC
Hi, I've been trying to build the week one code but I can't make it work.
I have tried the base version fix switching `base ^>=4.14.1.0` to `base ==4.14.0.0` but it doesn't work.
I also tried to use `ghc-8.10.2` instead of my current `ghc-8.10.5`, but it doesn't seem to work either.

### Here's the error:
```
Warning: Requested index-state 2021-06-10T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2021-06-09T23:01:39Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: cardano-crypto-class (user goal)
[__0] rejecting: cardano-crypto-class-2.0.0 (conflict: pkg-config package
libsodium-any, not found in the pkg-config database)
[__0] fail (backjumping, conflict set: cardano-crypto-class)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-crypto-class
```

**Device:** M1 mac with macOS BigSur 11.4

I would love some help thanks!

**Comment by Kaleb47** [comment] 2021-08-22 21:27
> Hi, I've been trying to build the week one code but I can't make it work.
> I have tried the base version fix switching `base ^>=4.14.1.0` to `base ==4.14.0.0` but it doesn't work.
> I also tried to use `ghc-8.10.2` instead of my current `ghc-8.10.5`, but it doesn't seem to work either.
> 
> ### Here's the error:
> ```
> Warning: Requested index-state 2021-06-10T00:00:00Z is newer than
> 'hackage.haskell.org'! Falling back to older state (2021-06-09T23:01:39Z).
> Resolving dependencies...
> cabal: Could not resolve dependencies:
> [__0] next goal: cardano-crypto-class (user goal)
> [__0] rejecting: cardano-crypto-class-2.0.0 (conflict: pkg-config package
> libsodium-any, not found in the pkg-config database)
> [__0] fail (backjumping, conflict set: cardano-crypto-class)
> After searching the rest of the dependency tree exhaustively, these were the
> goals I've had most trouble fulfilling: cardano-crypto-class
> ```
> 
> **Device:** M1 mac with macOS BigSur 11.4
> 
> I would love some help thanks!

I was able to build week 1 on the M1 big sur, but the problem is EnglishAuction.hs contract has 12 errors. Is that done on purpose because I'm pretty sure you're supposed to compile and test that code so why would it have so many errors?

**Comment by Kaleb47** [comment] 2021-08-22 21:28
> Hi, I've been trying to build the week one code but I can't make it work.
> I have tried the base version fix switching `base ^>=4.14.1.0` to `base ==4.14.0.0` but it doesn't work.
> I also tried to use `ghc-8.10.2` instead of my current `ghc-8.10.5`, but it doesn't seem to work either.
> 
> ### Here's the error:
> ```
> Warning: Requested index-state 2021-06-10T00:00:00Z is newer than
> 'hackage.haskell.org'! Falling back to older state (2021-06-09T23:01:39Z).
> Resolving dependencies...
> cabal: Could not resolve dependencies:
> [__0] next goal: cardano-crypto-class (user goal)
> [__0] rejecting: cardano-crypto-class-2.0.0 (conflict: pkg-config package
> libsodium-any, not found in the pkg-config database)
> [__0] fail (backjumping, conflict set: cardano-crypto-class)
> After searching the rest of the dependency tree exhaustively, these were the
> goals I've had most trouble fulfilling: cardano-crypto-class
> ```
> 
> **Device:** M1 mac with macOS BigSur 11.4
> 
> I would love some help thanks!

Be sure to install rosetta and use an intel-based text editor or else you're going to run into problems!

**Comment by bjing** [comment] 2021-11-01 05:38
If you are on Mac, just do a 
```
brew install libsodium
```
and you should be good. If not, try `cabal clean` before rebuilding.

**Comment by luisantonioig** [comment] 2023-05-25 14:14
Hi @Carlosted,

I hope this message finds you well.

I wanted to inform you that we have decided to close this issue as it pertains to an old branch of the course. Please note that these branches are not actively maintained and are kept for historical purposes.

We encourage you to utilize the branch that best suits your needs, whether it's the current version or any other relevant branch.

Please don't hesitate to reach out if you have any questions or require further assistance. We're here to help!

Thank you for your understanding and your valuable contributions.

**Closed by luisantonioig** 2023-05-25 14:14 UTC
